

import { CourseInterFace } from 'components/types'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'


const Course: NextPage = () => {
            const [course,setCourse]=useState<Array<CourseInterFace>>([])
            
   async function fetchCourse() {
    await fetch('data.json')
        .then(res=> res.json())
        .then(data => 
           setCourse(data)
            
        )
        .catch(err => console.error(err));
}
    
    useEffect(()=>{
       fetchCourse()
        
    },[])
    // console.dir(course)
   
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      
    </div>
  )
}

export default Course