import Banner from 'components/home/Banner'
import Course from 'components/home/Course'
import Navbar from 'components/shared/Navbar'
import { MainCourse } from 'components/types'
import { NextPage } from 'next'
import Head from 'next/head'

export const getStaticProps = async () => {
  const res = await fetch(' https://jsonkeeper.com/b/UFAZ')
  const data = await res.json()
  return {
    props: {
      data: data
    }
  }
}



const Home: NextPage<{data:MainCourse[]}> = ({data}) => {
  console.log(data)
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <Banner/>
      <Course data={data}/>
      
    </div>
  )
}

export default Home
