import Banner from "components/home/Banner";
import Course from "components/home/Course";
import Footer from "components/shared/Footer";
import Navbar from "components/shared/Navbar";
import { MainCourse } from "components/types";
import { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { State } from "redux/reducers";

const Home: NextPage<{ data: MainCourse[] }> = ({ data, reviews }: any) => {
  const dispatch = useDispatch();

  useEffect(() => {
    dispatch({
      type: "REVIEW_FETCH",
      payload: reviews,
    });
  }, [dispatch, reviews]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Banner />
      <Course data={data} />
      <Footer />
    </div>
  );
};

export default Home;
export const getServerSideProps = async () => {
  try {
    const res = await fetch(
      "https://fake-udemy-dashboard.vercel.app/assets/data.json"
    );

    const data = await res.json();

    const reviewRes = await fetch("https://jsonkeeper.com/b/QQK5");
    const reviews = await reviewRes.json();

    return {
      props: {
        data: data,
        reviews: reviews,
      },
    };
  } catch (err) {
    console.log("error", err);
  }
};
// https://jsonkeeper.com/b/WWJT
// http://localhost:3000/assets/data.json
// https://fake-udemy-dashboard.vercel.app/assets/data.json'
